c++: constexpr error with defaulted virtual dtor [PR93413]
We're rejecting the below testcase with

  error: 'virtual constexpr Base::~Base()' used before its definition
  error: 'virtual constexpr Derived::~Derived()' used before its definition

due to special handling in mark_used added by r181272 to defer synthesis
of virtual destructors until EOF (where we can set their linkage), which
in turn makes them effectively unusable during constexpr evaluation.

Fortunately it seems this special handling is unnecessary ever since
r208030 enabled us to tentatively set linkage of all defaulted virtual
destructors, including templated ones.  So this patch gets rid of this
special handling.

	PR c++/93413

gcc/cp/ChangeLog:

	* decl2.cc (mark_used): Don't defer synthesis of virtual
	functions.

gcc/testsuite/ChangeLog:

	* g++.dg/cpp2a/constexpr-virtual21.C: New test.