testsuite: Fix up test language requirements [PR94314]
With c++11 one gets:
Excess errors:
.../testsuite/g++.dg/pr94314-4.C:19:28: error: too many arguments to function 'void operator delete(void*)'
because C++ sized deallocation is a C++14 feature.

2020-04-17  Jakub Jelinek  <jakub@redhat.com>

	PR c++/94314
	* g++.dg/pr94314-4.C: Require c++14 rather than c++11.