testsuite: nodiscard-reason-nonstring.C FAIL in C++26
Since r14-5071, we emit an extra error for this test (the first one):

nodiscard-reason-nonstring.C:5:13: error: expected string-literal before numeric constant
nodiscard-reason-nonstring.C:5:36: error: 'nodiscard' attribute argument must be a string constant

so the test needs adjusting.

gcc/testsuite/ChangeLog:

	* g++.dg/cpp2a/nodiscard-reason-nonstring.C: Adjust dg-error.