testsuite: Fix up syntax errors in scan-tree-dump-times target selectors
On Thu, Mar 02, 2023 at 07:23:32PM +0100, Robin Dapp via Gcc-patches wrote:
> this patch changes SLP test expectations.  As we only vectorize when no
> more than one rgroup is present, no vectorization is performed.

This broke the tests, I'm seeing syntax errors:
ERROR: gcc.dg/vect/slp-3.c -flto -ffat-lto-objects: error executing dg-final: syntax error in target selector "target !  vect_partial_vectors || vect32  || s390_vx"
ERROR: gcc.dg/vect/slp-3.c: error executing dg-final: syntax error in target selector "target !  vect_partial_vectors || vect32  || s390_vx"
ERROR: gcc.dg/vect/slp-multitypes-11.c -flto -ffat-lto-objects: error executing dg-final: syntax error in target selector "target vect_unpack && vect_partial_vectors_usage_1 &&  ! s390_vx"
ERROR: gcc.dg/vect/slp-multitypes-11.c: error executing dg-final: syntax error in target selector "target vect_unpack && vect_partial_vectors_usage_1 &&  ! s390_vx"

The following patch fixes those.

2023-03-04  Jakub Jelinek  <jakub@redhat.com>

	* gcc.dg/vect/slp-3.c: Fix up syntax errors in scan-tree-dump-times
	target selectors.
	* gcc.dg/vect/slp-multitypes-11.c: Likewise.